//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinansApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borclar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Borclar()
        {
            this.Faturalar = new HashSet<Faturalar>();
            this.UrunSatis = new HashSet<UrunSatis>();
        }
    
        public int Id { get; set; }
        public Nullable<decimal> ToplamBorc { get; set; }
        public Nullable<decimal> Odenen { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> MusteriId { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faturalar> Faturalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrunSatis> UrunSatis { get; set; }
    }
}
