//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinansApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunSatis
    {
        public int Id { get; set; }
        public Nullable<int> UrunId { get; set; }
        public Nullable<int> SatisId { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<decimal> AraToplam { get; set; }
    
        public virtual Satislar Satislar { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
